/**
 * ERP May 10 - Enterprise 5 Core Modules Configuration
 * Business-focused presentation without technical clutter.
 */

export const ERP_MODULES = [
  {
    id: 'PH1',
    code: 'sales',
    name: 'Bán hàng & Quản lý khách hàng',
    shortName: 'Bán hàng',
    description: 'Quản lý báo giá, đơn đặt hàng thời trang, hợp đồng kinh doanh, hệ thống đại lý & phân phối May 10.',
    icon: 'ShoppingBag',
    route: '/sales',
    status: 'pending_development',
    statusBadge: {
      text: 'Đang triển khai',
      color: 'bg-gray-100 text-gray-700 border-gray-200',
    },
    tables: ['khach_hang', 'don_ban_hang', 'chi_tiet_don_ban_hang'],
    requiredPermission: 'sales.view',
    primaryColor: '#2563EB',
    features: [
      'Quản lý hồ sơ khách hàng may mặc & đối tác xuất khẩu',
      'Lập đơn đặt hàng bán (SO) & hợp đồng thời trang',
      'Theo dõi tiến độ giao hàng và doanh thu',
    ],
  },
  {
    id: 'PH2',
    code: 'production',
    name: 'Sản xuất & Kế hoạch NPL',
    shortName: 'Sản xuất',
    description: 'Hoạch định chuyền may, định mức kỹ thuật (BOM), lập lệnh sản xuất, theo dõi cắt may & kiểm tra KCS.',
    icon: 'Factory',
    route: '/production',
    status: 'pending_development',
    statusBadge: {
      text: 'Đang triển khai',
      color: 'bg-gray-100 text-gray-700 border-gray-200',
    },
    tables: ['dinh_muc_bom', 'lenh_san_xuat', 'chi_tiet_lenh_san_xuat', 'chuyen_may', 'tiem_do_san_xuat'],
    requiredPermission: 'production.view',
    primaryColor: '#059669',
    features: [
      'Xây dựng định mức nguyên phụ liệu may mặc (BOM)',
      'Lập kế hoạch chuyền may & phát hành Lệnh sản xuất (LSX)',
      'Theo dõi tiến độ hoàn thành sản phẩm may',
    ],
  },
  {
    id: 'PH3',
    code: 'purchasing',
    name: 'Mua hàng & Nhà cung cấp',
    shortName: 'Mua hàng',
    description: 'Quản lý đề xuất mua NPL, phát hành đơn mua hàng (PO), đánh giá nhà cung cấp dệt may & kiểm soát giá.',
    icon: 'ShoppingCart',
    route: '/purchasing',
    status: 'pending_development',
    statusBadge: {
      text: 'Đang triển khai',
      color: 'bg-gray-100 text-gray-700 border-gray-200',
    },
    tables: ['nha_cung_cap', 'don_mua_hang', 'chi_tiet_don_mua_hang'],
    requiredPermission: 'purchasing.view',
    primaryColor: '#D97706',
    features: [
      'Theo dõi đề xuất mua nguyên phụ liệu từ Kế hoạch SX',
      'Lập đơn mua hàng (PO) gửi nhà cung ứng vải/phụ liệu',
      'Đánh giá năng lực và lịch sử giao hàng của nhà cung cấp',
    ],
  },
  {
    id: 'PH4',
    code: 'warehouse',
    name: 'Kho & Quản lý vật tư',
    shortName: 'Kho & Vật tư',
    description: 'Quản trị toàn diện xuất - nhập - tồn, định vị kệ hàng, quản lý lô/cây vải hạn dùng, điều chuyển & kiểm kê.',
    icon: 'Warehouse',
    route: '/warehouse',
    status: 'active',
    statusBadge: {
      text: 'Đang vận hành',
      color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    },
    tables: [
      'kho',
      'vi_tri_kho',
      'lo_vat_tu',
      'ton_kho',
      'phieu_nhap_kho',
      'phieu_xuat_kho',
      'phieu_chuyen_kho',
      'phieu_kiem_ke',
    ],
    requiredPermission: 'warehouse.view',
    primaryColor: '#8B1E2D',
    features: [
      'Báo cáo số dư tồn kho, định vị vị trí kệ và quản lý lô vải FEFO',
      'Quy trình lập, duyệt Phiếu Nhập kho và Phiếu Xuất kho',
      'Điều chuyển vật tư giữa các phân xưởng và cân đối kiểm kê',
    ],
  },
  {
    id: 'PH5',
    code: 'accounting',
    name: 'Tài chính – Kế toán & Giá thành',
    shortName: 'Tài chính',
    description: 'Hạch toán kho tự động, sổ cái nhật ký chung, công nợ đối tác may mặc, chi phí đơn hàng & giá thành sản phẩm.',
    icon: 'Calculator',
    route: '/accounting',
    status: 'pending_development',
    statusBadge: {
      text: 'Đang triển khai',
      color: 'bg-gray-100 text-gray-700 border-gray-200',
    },
    tables: ['tai_khoan_ke_toan', 'but_toan_tong_hop', 'chi_tiet_but_toan', 'so_cai', 'bang_can_doi'],
    requiredPermission: 'accounting.view',
    primaryColor: '#6366F1',
    features: [
      'Tự động ghi nhận bút toán Nợ/Có khi phát sinh chứng từ kho',
      'Quản lý công nợ khách hàng và nhà cung cấp',
      'Tập hợp chi phí và tính giá thành đơn may',
    ],
  },
];
