import { useEffect, useRef, useState } from 'react';
import Icon from './Icon.jsx';
import { date, money } from './DocumentDetail.jsx';
import { fetchJournal, isJournalRequestCanceled, updateJournal } from '../services/journals.js';

const field='mt-1.5 h-9 w-full rounded-md border border-slate-200 bg-white px-3 text-xs outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100';

export default function JournalEditor({id,accounts,close,saved}){
  const dialog=useRef(null),busyRef=useRef(false);
  const[state,setState]=useState({loading:true}),[form,setForm]=useState({debitAccountId:'',creditAccountId:'',amount:'',description:''});
  const[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{dialog.current?.showModal()},[]);
  useEffect(()=>{const controller=new AbortController();setState({loading:true});setError('');fetchJournal(id,controller.signal).then(result=>{if(controller.signal.aborted||!result)return;const data=result.data;setState({data});setForm({debitAccountId:String(data.tai_khoan_no),creditAccountId:String(data.tai_khoan_co),amount:String(data.so_tien),description:data.mo_ta||''})}).catch(err=>{if(!isJournalRequestCanceled(err,controller.signal))setState({error:err.message})});return()=>controller.abort()},[id,retry]);
  const change=(key,value)=>setForm(old=>({...old,[key]:value}));
  async function submit(event){event.preventDefault();if(busyRef.current)return;setError('');if(!form.debitAccountId||!form.creditAccountId)return setError('Vui lòng chọn đầy đủ tài khoản Nợ và tài khoản Có.');if(form.debitAccountId===form.creditAccountId)return setError('Tài khoản Nợ và tài khoản Có phải khác nhau.');if(!/^\d{1,16}(\.\d{1,2})?$/.test(form.amount)||Number(form.amount)<=0)return setError('Số tiền phải lớn hơn 0 và có tối đa 2 chữ số thập phân.');if(!form.description.trim())return setError('Vui lòng nhập diễn giải bút toán.');busyRef.current=true;setBusy(true);try{const result=await updateJournal(id,{...form,description:form.description.trim()});saved(result.data)}catch(err){setError(err.message)}finally{busyRef.current=false;setBusy(false)}}
  const data=state.data;
  return <dialog ref={dialog} onClose={close} onCancel={event=>{if(busyRef.current)event.preventDefault()}} aria-labelledby="journal-editor-title" className="m-auto max-h-[90vh] w-[calc(100%_-_2rem)] max-w-2xl overflow-y-auto rounded-xl border border-slate-200 bg-white p-0 text-slate-700 shadow-xl backdrop:bg-slate-950/40"><form onSubmit={submit}><div className="panel-heading"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-600">Chỉnh sửa bút toán lỗi</p><h2 id="journal-editor-title">Sửa bút toán{data?` · ${data.ma_hach_toan}`:''}</h2><p className="mt-1 text-xs text-slate-500">Mã bút toán và chứng từ nguồn được giữ nguyên.</p></div><button type="button" disabled={busy} className="icon-button" aria-label="Đóng" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></div>
    {state.loading?<p role="status" className="p-8 text-center text-xs text-slate-500">Đang tải bút toán…</p>:state.error?<p role="alert" className="p-6 text-xs text-rose-700">{state.error}<button type="button" className="ml-2 underline" onClick={()=>setRetry(value=>value+1)}>Thử lại</button></p>:data&&<div className="space-y-4 p-5"><dl className="grid gap-3 rounded-lg border border-slate-100 bg-slate-50 p-4 sm:grid-cols-3"><div><dt className="text-[10px] text-slate-400">Mã bút toán</dt><dd className="mt-1 text-xs font-semibold text-[#173455]">{data.ma_hach_toan}</dd></div><div><dt className="text-[10px] text-slate-400">Chứng từ nguồn</dt><dd className="mt-1 text-xs font-semibold text-[#173455]">{data.ma_chung_tu}</dd></div><div><dt className="text-[10px] text-slate-400">Ngày hạch toán</dt><dd className="mt-1 text-xs font-semibold text-[#173455]">{date(data.ngay_hach_toan)}</dd></div></dl><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-slate-600">Tài khoản Nợ<select required className={field} value={form.debitAccountId} onChange={event=>change('debitAccountId',event.target.value)}><option value="">Chọn tài khoản Nợ</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.so_tai_khoan} · {account.ten_tai_khoan}</option>)}</select></label><label className="text-xs font-medium text-slate-600">Tài khoản Có<select required className={field} value={form.creditAccountId} onChange={event=>change('creditAccountId',event.target.value)}><option value="">Chọn tài khoản Có</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.so_tai_khoan} · {account.ten_tai_khoan}</option>)}</select></label><label className="text-xs font-medium text-slate-600">Số tiền<input required inputMode="decimal" className={field} value={form.amount} onChange={event=>change('amount',event.target.value)}/><small className="mt-1 block text-slate-400">Hiện tại: {money(data.so_tien)}</small></label><label className="text-xs font-medium text-slate-600 sm:col-span-2">Diễn giải<textarea required maxLength={10000} rows={3} className="mt-1.5 w-full rounded-md border border-slate-200 px-3 py-2 text-xs outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100" value={form.description} onChange={event=>change('description',event.target.value)}/></label></div>{error&&<p role="alert" className="text-xs text-rose-700">{error}</p>}</div>}
    <div className="flex justify-end gap-2 border-t border-slate-100 px-5 py-3"><button type="button" disabled={busy} className="rounded-md border border-slate-200 px-4 py-2 text-xs" onClick={()=>dialog.current?.close()}>Hủy</button><button disabled={busy||state.loading||Boolean(state.error)} className="rounded-md bg-[#255b98] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{busy?'Đang lưu…':'Lưu thay đổi'}</button></div></form></dialog>;
}
