import { useEffect, useMemo, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { money } from '../components/DocumentDetail.jsx';
import { fetchChiefAccountantOverview } from '../services/chiefAccountant.js';

const sourceLabels={documents:'Chứng từ',journals:'Hạch toán',debts:'Công nợ',costs:'Chi phí',costing:'Giá thành',orders:'Hiệu quả đơn hàng',reports:'Báo cáo tài chính'};
const tones={blue:'border-blue-200 text-blue-700 bg-blue-50',amber:'border-amber-200 text-amber-700 bg-amber-50',green:'border-emerald-200 text-emerald-700 bg-emerald-50',indigo:'border-indigo-200 text-indigo-700 bg-indigo-50',red:'border-rose-200 text-rose-700 bg-rose-50'};
const count=(value)=>value==null?'—':Number(value).toLocaleString('vi-VN');

export default function ChiefAccountantDashboard({navigate,canViewReports=false}){
  const[state,setState]=useState({loading:true});
  useEffect(()=>{const controller=new AbortController();setState({loading:true});fetchChiefAccountantOverview(controller.signal).then(result=>{if(result&&!controller.signal.aborted)setState(result)}).catch(error=>{if(!controller.signal.aborted)setState({error:error.message})});return()=>controller.abort()},[]);
  const view=useMemo(()=>{
    const data=state.data||{},documents=data.documents||{},journals=data.journals||{},debts=data.debts||{},costs=data.costs||{},costing=data.costing||{},orders=data.orders||{},reports=data.reports||{};
    const costingRows=costing.data||[],orderRows=orders.data||[],documentRows=documents.data||[],debtRows=debts.data||[];
    const missingCosting=costingRows.filter(item=>Number(item.so_luong_hoan_thanh)<=0||Number(item.so_dong_nguon)<=0||!item.gia_thanh_id);
    const warnings=[];
    documentRows.filter(item=>!item.da_hach_toan).forEach(item=>warnings.push({type:'Chứng từ chưa hạch toán',object:item.ma_chung_tu,status:'Chờ hạch toán',route:'/chung-tu'}));
    costingRows.filter(item=>Number(item.so_luong_hoan_thanh)<=0).forEach(item=>warnings.push({type:'Thiếu sản lượng',object:item.ma_lenh_san_xuat,status:'Chưa có sản lượng hoàn thành',route:'/gia-thanh'}));
    costingRows.filter(item=>Number(item.so_dong_nguon)<=0).forEach(item=>warnings.push({type:'Thiếu chi phí nguồn',object:item.ma_lenh_san_xuat,status:'Chưa có phiếu xuất sản xuất',route:'/chi-phi'}));
    orderRows.filter(item=>item.data_status==='insufficient').forEach(item=>warnings.push({type:'Hiệu quả đơn hàng',object:item.ma_don_ban,status:'Chưa đủ dữ liệu',route:'/hieu-qua-don-hang'}));
    debtRows.filter(item=>item.trang_thai_hien_thi==='qua_han').forEach(item=>warnings.push({type:'Công nợ quá hạn',object:item.ma_doi_tuong||item.ten_doi_tuong,status:'Quá hạn',route:'/cong-no'}));
    return {data,documents,journals,debts,costs,costing,reports,missingCosting,warnings};
  },[state.data]);
  const kpis=[
    ['Tổng số chứng từ',count(view.documents.summary?.total),'file','blue'],['Chứng từ chờ hạch toán',count(view.documents.summary?.unposted),'clock','amber'],
    ['Tổng số bút toán',count(view.journals.summary?.total),'book','indigo'],['Tổng phải thu',money(view.debts.summary?.receivable),'wallet','blue'],
    ['Tổng phải trả',money(view.debts.summary?.payable),'wallet','amber'],['Chi phí đang tập hợp',money(view.costs.summary?.known_cost_total),'layers','green'],
    ['Đối tượng thiếu dữ liệu giá thành',state.data?.costing?count(view.missingCosting.length):'—','warning','red'],['Báo cáo tài chính đã lưu',state.data?.reports?count(view.reports.total):'—','report','indigo'],
  ];
  const totalDebt=Number(view.debts.summary?.receivable||0)+Number(view.debts.summary?.payable||0),receivableShare=totalDebt?Number(view.debts.summary.receivable)/totalDebt*100:0;
  return <div className="space-y-5"><header className="rounded-2xl border border-slate-200 bg-[#fbfdff] px-5 py-4 shadow-sm"><nav className="text-xs text-slate-500">Tài chính - Kế toán <span>›</span> Tổng quan Kế toán trưởng</nav><div className="mt-3 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><Icon name="chart"/></span><div><h1 className="text-2xl font-bold text-[#173455]">Tổng quan Kế toán trưởng</h1><p className="mt-1 text-sm text-slate-500">Giám sát chứng từ, công nợ, chi phí, giá thành và báo cáo từ dữ liệu hiện có.</p></div></div></header>
    {canViewReports&&<div className="flex justify-end"><a href="/bao-cao-tai-chinh" onClick={event=>navigate(event,'/bao-cao-tai-chinh')} className="inline-flex h-9 items-center gap-2 rounded-lg border border-blue-200 bg-white px-4 text-xs font-semibold text-blue-700 hover:bg-blue-50"><Icon name="download" className="h-4 w-4"/>Xuất báo cáo</a></div>}
    {state.loading?<section className="panel p-10 text-center text-sm text-slate-500">Đang tổng hợp dữ liệu…</section>:state.error?<section role="alert" className="panel border-rose-200 p-6 text-sm text-rose-700">{state.error}</section>:<>
      {state.errors?.length>0&&<section role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900"><strong>Một số nguồn chưa tải được:</strong> {state.errors.map(item=>sourceLabels[item.source]||item.source).join(', ')}. Các khối còn lại vẫn dùng dữ liệu API đã tải thành công.</section>}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([label,value,icon,tone])=><article key={label} className="panel flex min-h-28 items-start justify-between p-4"><div><p className="text-xs font-medium text-slate-500">{label}</p><strong className="mt-3 block text-xl font-bold tabular-nums text-[#173455]">{value}</strong></div><span className={`flex h-9 w-9 items-center justify-center rounded-lg border ${tones[tone]}`}><Icon name={icon} className="h-4 w-4"/></span></article>)}</section>
      <section className="grid gap-4 lg:grid-cols-3"><article className="panel p-5"><h2 className="font-semibold text-[#173455]">Trạng thái chứng từ</h2><p className="mt-1 text-xs text-slate-500">Suy ra từ liên kết bút toán thật</p>{view.documents.summary?<div className="mt-5"><div className="flex justify-between text-xs"><span>Đã hạch toán</span><strong>{count(view.documents.summary.posted)} / {count(view.documents.summary.total)}</strong></div><div className="mt-2 h-2 overflow-hidden rounded bg-slate-100"><i className="block h-full bg-blue-600" style={{width:`${view.documents.summary.total?view.documents.summary.posted/view.documents.summary.total*100:0}%`}}/></div><p className="mt-3 text-xs text-slate-500">Chờ hạch toán: {count(view.documents.summary.unposted)}</p></div>:<p className="mt-5 text-xs text-slate-500">Chưa có dữ liệu chứng từ.</p>}</article>
        <article className="panel p-5"><h2 className="font-semibold text-[#173455]">Cơ cấu công nợ</h2><p className="mt-1 text-xs text-slate-500">Giá trị còn phải thu và phải trả</p>{totalDebt>0?<div className="mt-5"><div className="flex h-3 overflow-hidden rounded-full bg-slate-100"><i className="bg-blue-600" style={{width:`${receivableShare}%`}}/><i className="bg-amber-500" style={{width:`${100-receivableShare}%`}}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><span className="text-slate-500">Phải thu</span><strong className="mt-1 block text-blue-700">{money(view.debts.summary.receivable)}</strong></div><div><span className="text-slate-500">Phải trả</span><strong className="mt-1 block text-amber-700">{money(view.debts.summary.payable)}</strong></div></div></div>:<p className="mt-5 text-xs text-slate-500">Không có giá trị công nợ còn lại.</p>}</article>
        <article className="panel p-5"><h2 className="font-semibold text-[#173455]">Tình trạng dữ liệu giá thành</h2><p className="mt-1 text-xs text-slate-500">Theo lệnh sản xuất trong API hiện tại</p>{state.data?.costing?<div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-lg bg-emerald-50 p-3"><span className="text-xs text-emerald-700">Đủ dữ liệu</span><strong className="mt-1 block text-xl text-emerald-800">{count((view.costing.data||[]).length-view.missingCosting.length)}</strong></div><div className="rounded-lg bg-amber-50 p-3"><span className="text-xs text-amber-700">Cần kiểm tra</span><strong className="mt-1 block text-xl text-amber-800">{count(view.missingCosting.length)}</strong></div></div>:<p className="mt-5 text-xs text-slate-500">Chưa có dữ liệu giá thành.</p>}</article></section>
      <section className="panel overflow-hidden"><div className="panel-heading"><div><h2>Cảnh báo cần theo dõi</h2><p className="mt-1 text-xs text-slate-500">Chỉ bao gồm cảnh báo suy ra từ API thật</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">{view.warnings.length} cảnh báo</span></div>{view.warnings.length?<div className="divide-y divide-slate-100">{view.warnings.map((item,index)=><article key={`${item.type}-${item.object}-${index}`} className="flex flex-wrap items-center gap-4 px-5 py-3 text-sm"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-50 text-amber-700"><Icon name="warning" className="h-4 w-4"/></span><div className="min-w-40 flex-1"><strong className="text-[#173455]">{item.type}</strong><p className="mt-0.5 text-xs text-slate-500">{item.object}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{item.status}</span><a href={item.route} onClick={event=>navigate(event,item.route)} className="text-xs font-semibold text-blue-700 hover:underline">Xem chi tiết</a></article>)}</div>:<p className="p-6 text-center text-sm text-slate-500">Không phát hiện cảnh báo từ dữ liệu hiện tại.</p>}</section>
    </>}</div>;
}
