import { useEffect, useMemo, useRef, useState } from 'react';
import Icon from '../components/Icon.jsx';
import { date, money } from '../components/DocumentDetail.jsx';
import { fetchDebt, fetchDebtFilters, fetchDebts } from '../services/debts.js';
import './Debts.css';

const defaults = { q: '', type: '', status: '', from: '', to: '', page: 1, pageSize: 20 };
const control = 'debt-control mt-1 w-full border bg-white outline-none';
const labels = { phai_thu: 'Phải thu', phai_tra: 'Phải trả', da_thanh_toan: 'Đã thanh toán', mot_phan: 'Thanh toán một phần', chua_thanh_toan: 'Chưa thanh toán', qua_han: 'Quá hạn', sap_den_han: 'Sắp đến hạn' };
const label = (value) => labels[value] || value || 'Chưa có trạng thái';
const statusTone = (value) => value === 'da_thanh_toan' ? 'success' : value === 'qua_han' ? 'danger' : value === 'sap_den_han' || value === 'chua_thanh_toan' ? 'warning' : value === 'mot_phan' ? 'info' : 'neutral';
const safeNumber = (value) => Number.isFinite(Number(value)) ? Number(value) : 0;
const percent = (part, total) => total > 0 ? Math.round(part / total * 100) : 0;
const compactMoney = (value) => new Intl.NumberFormat('vi-VN', { notation: 'compact', maximumFractionDigits: 1 }).format(safeNumber(value));

function DebtBadge({ value }) { return <span className={`debt-status ${statusTone(value)}`}>{value === 'qua_han' && <Icon name="warning" />}{label(value)}</span>; }

function DebtDetail({ id, close }) {
  const dialog = useRef(null);
  const [state, setState] = useState({ loading: true });
  useEffect(() => { dialog.current.showModal(); }, []);
  useEffect(() => { const controller = new AbortController(); fetchDebt(id, controller.signal).then((data) => { if (!controller.signal.aborted && data) setState(data); }).catch((error) => { if (!controller.signal.aborted) setState({ error: error.message }); }); return () => controller.abort(); }, [id]);
  const data = state.data;
  const overdue = data?.trang_thai_hien_thi === 'qua_han';
  return <dialog ref={dialog} onClose={close} className="debt-dialog m-auto max-h-[90vh] w-[calc(100%_-_2rem)] max-w-3xl overflow-y-auto border bg-white p-0 text-slate-700 shadow-xl backdrop:bg-slate-950/40"><div className="debt-dialog-header"><div><p>CHI TIẾT CÔNG NỢ</p><h2>{data?.ten_doi_tuong || 'Đang tải…'}</h2></div><button autoFocus className="icon-button" onClick={() => dialog.current.close()} aria-label="Đóng"><Icon name="close" /></button></div>
    {state.loading && <p className="debt-state">Đang tải chi tiết…</p>}{state.error && <p className="debt-state error">{state.error}</p>}{data && <div className="debt-detail-body">{overdue && <div className="debt-overdue-alert"><Icon name="warning" /><div><strong>Khoản công nợ này đã quá hạn</strong><p>Cần kiểm tra và xử lý theo quy trình công nợ hiện hành.</p></div></div>}
      <section className="debt-detail-section"><h3>Thông tin đối tượng</h3><dl><div><dt>Đối tượng</dt><dd>{data.ten_doi_tuong || '—'}</dd></div><div><dt>Mã đối tượng</dt><dd>{data.ma_doi_tuong || '—'}</dd></div><div><dt>Loại công nợ</dt><dd><span className={`debt-type ${data.loai_cong_no}`}>{label(data.loai_cong_no)}</span></dd></div></dl></section>
      <section className="debt-detail-section"><h3>Thông tin chứng từ</h3><dl><div><dt>Chứng từ / Hóa đơn</dt><dd className="debt-document">{data.ma_hoa_don_hien_thi || '—'}</dd></div><div><dt>Ngày tạo</dt><dd>{date(data.ngay_tao)}</dd></div><div><dt>Ngày đáo hạn</dt><dd className={overdue ? 'debt-danger-text' : ''}>{overdue && <Icon name="warning" />}{date(data.ngay_dao_han)}</dd></div></dl></section>
      <section className="debt-detail-section debt-value-section"><h3>Giá trị và trạng thái</h3><dl><div><dt>Số phát sinh</dt><dd>{money(data.so_tien_phat_sinh)}</dd></div><div><dt>Đã thanh toán</dt><dd className="debt-paid-text">{money(data.so_tien_da_thanh_toan)}</dd></div><div><dt>Còn lại</dt><dd className={overdue ? 'debt-danger-text' : 'debt-remaining-text'}>{money(data.so_tien_con_lai)}</dd></div><div><dt>Trạng thái</dt><dd><DebtBadge value={data.trang_thai_hien_thi} /></dd></div></dl></section>
      <section className="debt-detail-section"><h3>Lịch sử thanh toán</h3>{data.payments?.length ? <div className="overflow-x-auto"><table className="erp-table min-w-[600px]"><thead><tr><th className="text-left">Mã thanh toán</th><th className="text-left">Ngày</th><th className="text-right">Số tiền</th><th className="text-left">Hình thức</th><th className="text-left">Trạng thái</th></tr></thead><tbody>{data.payments.map((item) => <tr key={item.id}><td>{item.ma_thanh_toan_ncc}</td><td>{date(item.ngay_thanh_toan)}</td><td className="text-right font-semibold tabular-nums">{money(item.so_tien_thanh_toan)}</td><td>{item.hinh_thuc_thanh_toan || '—'}</td><td>{label(item.trang_thai)}</td></tr>)}</tbody></table></div> : <p className="debt-detail-empty">Chưa có dữ liệu lịch sử thanh toán chi tiết.</p>}</section>
    </div>}</dialog>;
}

export default function Debts() {
  const [draft, setDraft] = useState(defaults), [query, setQuery] = useState(defaults);
  const [filters, setFilters] = useState({ types: [], statuses: [] });
  const [state, setState] = useState({ loading: true });
  const [filterError, setFilterError] = useState(''), [validation, setValidation] = useState('');
  const [selected, setSelected] = useState(null);
  useEffect(() => { const controller = new AbortController(); fetchDebtFilters(controller.signal).then((data) => { if (!controller.signal.aborted && data) setFilters(data); }).catch((error) => { if (!controller.signal.aborted) setFilterError(error.message); }); return () => controller.abort(); }, []);
  useEffect(() => { const controller = new AbortController(); setState({ loading: true }); fetchDebts(query, controller.signal).then((data) => { if (!controller.signal.aborted && data) setState(data); }).catch((error) => { if (!controller.signal.aborted) setState({ error: error.message }); }); return () => controller.abort(); }, [query]);
  const change = (key, value) => setDraft((old) => ({ ...old, [key]: value }));
  const submit = (event) => { event.preventDefault(); if (draft.from && draft.to && draft.from > draft.to) { setValidation('Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.'); return; } setValidation(''); setQuery({ ...draft, page: 1 }); };
  const reset = () => { setDraft(defaults); setQuery({ ...defaults }); setValidation(''); };
  const summary = state.summary, rows = state.data || [], pagination = state.pagination;
  const receivable = safeNumber(summary?.receivable), payable = safeNumber(summary?.payable), totalDebt = receivable + payable;
  const attention = useMemo(() => rows.filter((row) => ['qua_han', 'sap_den_han'].includes(row.trang_thai_hien_thi)).sort((a, b) => (a.trang_thai_hien_thi === 'qua_han' ? 0 : 1) - (b.trang_thai_hien_thi === 'qua_han' ? 0 : 1) || safeNumber(b.so_tien_con_lai) - safeNumber(a.so_tien_con_lai)).slice(0, 5), [rows]);
  return <div className="debts-page"><header className="debt-page-header"><nav>Tài chính <span>›</span> Công nợ</nav><div className="flex items-center gap-3"><span><Icon name="wallet" /></span><div><h1>Công nợ</h1><p>Theo dõi các khoản phải thu, phải trả và tình trạng thanh toán.</p></div></div></header>
    <section className="debt-kpis">{[['Tổng phải thu', money(summary?.receivable), 'wallet', 'blue', 'Giá trị còn phải thu'], ['Tổng phải trả', money(summary?.payable), 'book', 'orange', 'Giá trị còn phải trả'], ['Quá hạn', summary?.overdue ?? '—', 'warning', safeNumber(summary?.overdue) > 0 ? 'red active-alert' : 'red', 'Khoản còn dư đã quá hạn'], ['Sắp đến hạn', summary?.due_soon ?? '—', 'calendar', 'amber', 'Trong vòng 7 ngày']].map(([title, value, icon, tone, note]) => <article key={title} className={`debt-kpi ${tone}`}><div><small>{title}</small><strong>{value}</strong><p>{note}</p></div><span><Icon name={icon} /></span></article>)}</section>
    <section className="debt-charts"><article className="panel debt-allocation"><div className="panel-heading"><div><h2>Phân bổ công nợ</h2><p>Theo giá trị còn lại</p></div></div><div className="debt-donut-layout">{totalDebt > 0 ? <div className="debt-donut" style={{ background: `radial-gradient(circle, white 53%, transparent 55%), conic-gradient(#2563a6 0 ${percent(receivable, totalDebt)}%, #d9822b ${percent(receivable, totalDebt)}% 100%)` }}><strong>{compactMoney(totalDebt)}</strong><span>Tổng còn lại</span></div> : <div className="debt-donut empty"><strong>0</strong><span>Chưa có dư nợ</span></div>}<ul><li><i className="receivable" /><span><b>PHẢI THU</b><small>{percent(receivable, totalDebt)}%</small></span><strong>{money(summary?.receivable)}</strong></li><li><i className="payable" /><span><b>PHẢI TRẢ</b><small>{percent(payable, totalDebt)}%</small></span><strong>{money(summary?.payable)}</strong></li></ul></div></article><article className="panel"><div className="panel-heading"><div><h2>Tình trạng thanh toán</h2><p>Số khoản theo trạng thái thực tế</p></div></div><div className="payment-status-chart">{summary?.statuses?.length ? summary.statuses.map((item) => { const share = percent(item.count, safeNumber(summary.total)); return <div className="payment-status-row" key={item.status}><div><span>{item.status === 'qua_han' && <Icon name="warning" />}<i className={statusTone(item.status)} />{label(item.status)}</span><strong>{item.count} khoản · {share}%</strong></div><div className="payment-track"><i className={statusTone(item.status)} style={{ width: `${share}%` }} /></div></div>; }) : <p className="debt-analytics-empty">Chưa có dữ liệu trạng thái thanh toán.</p>}</div></article></section>
    <section className="panel debt-attention"><div className="panel-heading"><div><h2>Công nợ cần chú ý</h2><p>Ưu tiên quá hạn và sắp đến hạn trong kết quả hiện tại</p></div><span>{attention.length} khoản</span></div>{attention.length ? <div className="debt-attention-list">{attention.map((row) => <button type="button" key={row.id} className={row.trang_thai_hien_thi} onClick={() => setSelected(row.id)}><span className="attention-icon"><Icon name={row.trang_thai_hien_thi === 'qua_han' ? 'warning' : 'clock'} /></span><span><strong>{row.ten_doi_tuong || '—'}</strong><small>{label(row.loai_cong_no)} · {row.ma_hoa_don_hien_thi || 'Chưa có mã chứng từ'}</small></span><b>{money(row.so_tien_con_lai)}</b><span className="attention-date">{date(row.ngay_dao_han)}</span><DebtBadge value={row.trang_thai_hien_thi} /></button>)}</div> : <div className="debt-attention-empty"><span><Icon name="check" /></span><div><strong>Không có khoản công nợ cần cảnh báo.</strong><p>Không có khoản quá hạn hoặc sắp đến hạn trong kết quả hiện tại.</p></div></div>}</section>
    <form onSubmit={submit} className="panel debt-filter"><label className="debt-search">Tìm kiếm đối tượng<div className="relative"><Icon name="search" /><input className={`${control} pl-10`} value={draft.q} onChange={(e) => change('q', e.target.value)} placeholder="Tên, mã đối tượng hoặc hóa đơn..." /></div></label><label>Loại công nợ<select className={control} value={draft.type} onChange={(e) => change('type', e.target.value)}><option value="">Tất cả</option>{filters.types.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>Trạng thái<select className={control} value={draft.status} onChange={(e) => change('status', e.target.value)}><option value="">Tất cả trạng thái</option>{filters.statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><label>Từ ngày<input type="date" className={control} value={draft.from} onChange={(e) => change('from', e.target.value)} /></label><label>Đến ngày<input type="date" className={control} value={draft.to} onChange={(e) => change('to', e.target.value)} /></label><button type="button" onClick={reset} className="debt-reset">Đặt lại</button><button className="debt-search-button"><Icon name="search" />Tìm kiếm</button>{(validation || filterError) && <p className="debt-filter-error">{validation || filterError}</p>}</form>
    <section className="panel overflow-hidden debt-list-panel"><div className="panel-heading"><div><h2>Danh sách công nợ</h2><p>Theo ngày đáo hạn</p></div><span className="debt-count">{pagination?.total ?? '—'} khoản</span></div>{state.loading ? <p className="debt-state">Đang tải công nợ…</p> : state.error ? <p className="debt-state error">{state.error}</p> : !rows.length ? <p className="debt-state">Không có khoản công nợ phù hợp với bộ lọc.</p> : <div className="overflow-x-auto"><table className="erp-table debt-table min-w-[1180px]"><thead><tr>{['STT', 'Đối tượng', 'Loại công nợ', 'Chứng từ / Hóa đơn', 'Số phát sinh', 'Đã thanh toán', 'Còn lại', 'Ngày đáo hạn', 'Trạng thái', 'Thao tác'].map((title) => <th key={title} className={['Số phát sinh','Đã thanh toán','Còn lại'].includes(title) ? 'text-right' : title === 'Thao tác' ? 'text-center' : 'text-left'}>{title}</th>)}</tr></thead><tbody>{rows.map((row, index) => { const overdue = row.trang_thai_hien_thi === 'qua_han', dueSoon = row.trang_thai_hien_thi === 'sap_den_han'; return <tr key={row.id} className={overdue ? 'debt-row-overdue' : ''}><td className="text-slate-400">{(pagination.page - 1) * pagination.pageSize + index + 1}</td><td><strong className="debt-party">{row.ten_doi_tuong || '—'}</strong><small>{row.ma_doi_tuong || 'Chưa có mã'}</small></td><td><span className={`debt-type ${row.loai_cong_no}`}>{label(row.loai_cong_no)}</span></td><td><span className="debt-document">{row.ma_hoa_don_hien_thi || '—'}</span></td><td className="debt-amount">{money(row.so_tien_phat_sinh)}</td><td className="debt-amount debt-paid-text">{money(row.so_tien_da_thanh_toan)}</td><td className={`debt-amount debt-remaining ${overdue ? 'danger' : dueSoon ? 'warning' : ''}`}>{overdue && <Icon name="warning" />}{money(row.so_tien_con_lai)}</td><td><span className={`debt-due-date ${overdue ? 'danger' : dueSoon ? 'warning' : ''}`}>{overdue && <Icon name="warning" />}{date(row.ngay_dao_han)}</span></td><td><DebtBadge value={row.trang_thai_hien_thi} /></td><td className="text-center"><button className="icon-button mx-auto" onClick={() => setSelected(row.id)} aria-label={`Xem công nợ ${row.ten_doi_tuong}`}><Icon name="eye" /></button></td></tr>; })}</tbody></table></div>}{pagination && <div className="debt-pagination"><span>{pagination.total} bản ghi</span><div><button disabled={pagination.page <= 1} onClick={() => setQuery((old) => ({ ...old, page: old.page - 1 }))}>Trước</button><span>{pagination.page} / {pagination.totalPages}</span><button disabled={pagination.page >= pagination.totalPages} onClick={() => setQuery((old) => ({ ...old, page: old.page + 1 }))}>Sau</button></div></div>}</section>
    {selected && <DebtDetail id={selected} close={() => setSelected(null)} />}
  </div>;
}
